[package]
name = "{{ project-name }}"
version = "0.1.0"
edition = "2021"

[features]
default = ["bevy/dynamic_linking"]

[dependencies]
bevy = "0.12.0"
slowchop_console = { version = "0.1.1" }
leafwing-input-manager = "0.11.1"

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
# opt-level = 3 has some segfault issues
[profile.dev.package."*"]
opt-level = 2
