create:
    cd ../.. && cargo generate bevy-template -n test-bevy-template

# Copy back from test-bevy-template, replacing the existing files
# and replace "test-bevy-template" with "{{ project-name }}"
sync:
    rsync -r \
        --exclude .git \
        --exclude target \
        --exclude Cargo.lock \
        --exclude .cargo \
        --exclude out \
        ../../test-bevy-template/ ..

    fd . .. -t f \
        -E dev \
        -E out \
        -E assets \
        -x sed -i '' 's/test-bevy-template/\{\{ project-name \}\}/g'
